### ISSUE TITLE
Fail to test the code

### ISSUE THREAD

**Issue by Dong142857** [Twizwei/in-n-out#1]
Thanks for your excellent work!

I followed the README's guidance to test the code, but encountered some strange output logs. Nothing is saved in './results/rednose2/eval/eyeglasses_smoothed_0429' except for some empty directories. Is there something wrong with the configuration?

```
(ngp-torch) xjd@CVI-DGX:~/workspace/in-n-out/eg3d$ bash scripts/run_test_styleclip.sh rednose2 eyeglasses ckpts/rednose2
rednose2
Getting new latent codes...Loading from checkpoint: ./mapper_results/eyeglasses/checkpoints/best_model.pt
Traceback (most recent call last):
  File "mapper/inference_eg3d.py", line 125, in <module>
    run(test_opts)
  File "mapper/inference_eg3d.py", line 53, in run
    net = StyleCLIPMapper(opts, G, load_G=False)
  File "./mapper/styleclip_mapper.py", line 24, in __init__
    self.load_weights(load_G)
  File "./mapper/styleclip_mapper.py", line 43, in load_weights
    self.mapper.load_state_dict(get_keys(ckpt, 'mapper'), strict=True)
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1668, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LevelsMapper:
        Missing key(s) in state_dict: "fine_mapping.mapping.1.weight", "fine_mapping.mapping.1.bias", "fine_mapping.mapping.2.weight", "fine_mapping.mapping.2.bias", "fine_mapping.mapping.3.weight", "fine_mapping.mapping.3.bias", "fine_mapping.mapping.4.weight", "fine_mapping.mapping.4.bias".
Loading from checkpoint: ./mapper_results/eyeglasses/checkpoints/best_model.pt
  0%|                                                                                                                                                                           | 0/84 [00:00<?, ?it/s]
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84/84 [00:26<00:00,  3.19it/s]
Runtime 0.0824+-0.2786
Rendering edited results...Saving results...
./results/rednose2/eval/eyeglasses_smoothed_0429
0it [00:00, ?it/s]
0it [00:00, ?it/s]
```

**Comment by Twizwei** [comment]
Oh yes, this is because for "eyeglasses" checkpoint, it doesn't have fine mapper. Use a flag `--no_fine_mapper` should bypass this error. 

```
python mapper/inference_eg3d.py --exp_dir=../${ExpDir} --checkpoint_path=${StyleClipCkpt} --latents_test_path=../${LatentPath} --camera_params_path=../${CamParaPath} --factor_step 0.06 --save_latents --no_fine_mapper
```

**Comment by Twizwei** [comment]
Also need to change this [line](https://github.com/Twizwei/in-n-out/blob/main/eg3d/scripts/run_test_styleclip.sh#L6) to your data directory. I will update the code. Thanks! 

```
TargetPath=./data/wildvideos/${VideoName}
```
